name: Unit Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  PHPUnit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.3,7.4]
        os: [ubuntu-latest]

    name: PHP${{ matrix.php }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Configure Application
        run: bin/ci
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/pest